spring:
  application:    name: servicio-config-server  cloud:    config:      server:        git:          uri: https://github.com/jordiDevel/udemy-microsrv-config-repo.git
    
server:
  port: 8888
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:      show-details: always
    metrics:
      enabled: true
    prometheus:      enabled: true
  metrics:    export:      prometheus:        enabled: true
